import { useEffect, useState } from "react";
import api from "../api";
import TopBar from "../components/TopBar";
import { LABELS } from "../labels";
import Icon from "../components/ui/Icon";
import Toast from "../components/ui/Toast";
import BudgetManagement from "./BudgetManagement";

const roles = { ADMIN: "مدير", SUPER_ADMIN: "مدير عام", TEACHER: "أستاذ", RESTAURANT_MANAGER: "مشرف المطعم" };
const actions = { SUBMIT_ABSENCE: "تسجيل غياب", SCAN_MEAL: "صرف وجبة", EDIT_INVENTORY: "تعديل مخزون", CREATE_USER: "إنشاء حساب", DEACTIVATE_USER: "تعطيل حساب", EXPORT_REPORT: "تصدير تقرير" };
const dates = () => { const end = new Date(), start = new Date(end); start.setDate(end.getDate() - 6); const iso = d => d.toISOString().slice(0, 10); return { start: iso(start), end: iso(end) }; };

export default function AdminDashboard() {
  const [overview, setOverview] = useState(null), [stats, setStats] = useState(null), [logs, setLogs] = useState([]), [budgetSummary, setBudgetSummary] = useState(null), [toast, setToast] = useState(null);
  function notify(message, type = "success") { setToast({ message, type }); window.setTimeout(() => setToast(null), 4000); }
  const [range, setRange] = useState(dates), [error, setError] = useState(""), [loading, setLoading] = useState(true), [exporting, setExporting] = useState(false), [showManage, setShowManage] = useState(false), [newClass, setNewClass] = useState(""), [newStudent, setNewStudent] = useState({ full_name: "", barcode: "", classroom_id: "" }), [active, setActive] = useState("dashboard"), [newItem, setNewItem] = useState({ name: "", quantity: "", unit: "كغ", low_stock_threshold: "5", image_url: "" }), [gradeRows, setGradeRows] = useState([]), [gradeTerm, setGradeTerm] = useState("الفصل الثالث"), [gradeSubject, setGradeSubject] = useState("التربية البدنية والرياضية"), [profile, setProfile] = useState(null), [profileDraft, setProfileDraft] = useState({}), [importFile, setImportFile] = useState(null), [importClass, setImportClass] = useState(""), [importResult, setImportResult] = useState(null), [preview, setPreview] = useState(null), [newUser, setNewUser] = useState({ username: "", password: "", full_name: "", role: "TEACHER" }), [studentSearch, setStudentSearch] = useState(""), [absenceRows, setAbsenceRows] = useState([]), [absenceRange, setAbsenceRange] = useState({ start: "", end: "" }), [absenceClass, setAbsenceClass] = useState(""), [schedules, setSchedules] = useState([]), [schedule, setSchedule] = useState({ teacher_id: "", classroom_id: "", day: "0", period: "MORNING" }), [config, setConfig] = useState(null), [facilities, setFacilities] = useState([]), [quotas, setQuotas] = useState([]), [resourceForm, setResourceForm] = useState({ name: "", kind: "CLASSROOM", capacity: "" }), [quotaForm, setQuotaForm] = useState({ level: "", subject: "", lessons_per_week: "1", minutes_per_lesson: "45" });
  async function load() { try { const [o, s, l, b] = await Promise.all([api.get("/api/admin/dashboard/overview"), api.get("/api/admin/dashboard/stats"), api.get("/api/admin/audit-logs?limit=12"), api.get("/api/admin/budget/summary")]); setOverview(o.data); setStats(s.data); setLogs(l.data); setBudgetSummary(b.data); setError(""); } catch { setError("تعذّر تحميل لوحة المدير"); } finally { setLoading(false); } }
  // مزامنة لوحة المدير مع الخادم عند الدخول وكل 30 ثانية؛ الاستثناء مقصود هنا.
  // oxlint-disable-next-line react(set-state-in-effect)
  useEffect(() => { load(); loadSchedules(); const timer = setInterval(load, 30000); return () => clearInterval(timer); }, []);
  async function exportPdf() { setExporting(true); try { const r = await api.get("/api/admin/reports/absences.pdf", { params: range, responseType: "blob" }); const u = URL.createObjectURL(r.data), a = document.createElement("a"); a.href = u; a.download = `غياب-${range.start}-${range.end}.pdf`; a.click(); URL.revokeObjectURL(u); } catch { setError("تعذّر تصدير التقرير"); } finally { setExporting(false); } }
  async function exportAbsencesXlsx() { try { const r = await api.get("/api/admin/reports/absences.xlsx", { params: range, responseType: "blob" }); const u = URL.createObjectURL(r.data), a = document.createElement("a"); a.href = u; a.download = `غياب-${range.start}-${range.end}.xlsx`; a.click(); URL.revokeObjectURL(u); } catch { setError("تعذّر تصدير Excel"); } }
  async function addClass(e) { e.preventDefault(); if (!newClass.trim()) return; await api.post("/api/admin/classrooms", { name: newClass }); setNewClass(""); load(); }
  async function addStudent(e) { e.preventDefault(); if (!newStudent.full_name || !newStudent.barcode || !newStudent.classroom_id) return; try { await api.post("/api/admin/students", newStudent); setNewStudent({ full_name: "", barcode: "", classroom_id: "" }); notify("تم حفظ ملف التلميذ"); load(); } catch (e) { setError(e.response?.data?.detail || "تعذّرت إضافة التلميذ"); notify("تعذّرت إضافة التلميذ", "error"); } }
  async function addInventory(e) { e.preventDefault(); try { await api.post("/api/admin/inventory", { ...newItem, quantity: Number(newItem.quantity), low_stock_threshold: Number(newItem.low_stock_threshold) }); setNewItem({ name: "", quantity: "", unit: "كغ", low_stock_threshold: "5", image_url: "" }); notify("تم حفظ المنتج في المخزون"); load(); } catch (e) { setError(e.response?.data?.detail || "تعذّرت إضافة المنتج"); notify("تعذّرت إضافة المنتج", "error"); } }
  async function loadGrades() { try { const { data } = await api.get("/api/admin/grades", { params: { term: gradeTerm, subject: gradeSubject } }); setGradeRows(data); } catch { setError("تعذّر تحميل دفتر النقاط"); } }
  async function loadAbsences() { try { const { data } = await api.get("/api/admin/absences", { params: { ...absenceRange, classroom_id: absenceClass || undefined } }); setAbsenceRows(data); } catch { setError("تعذّر تحميل سجل الغياب"); } }
  async function loadSchedules() { try { const [{ data: rows }, { data: cfg }, { data: fs }, { data: qs }] = await Promise.all([api.get("/api/admin/schedules"), api.get("/api/admin/schedule-config"), api.get("/api/admin/facilities"), api.get("/api/admin/subject-quotas")]); setSchedules(rows); setConfig(cfg); setFacilities(fs); setQuotas(qs); } catch { setError("تعذّر تحميل إعدادات الدوام"); } }
  async function addFacility(e) { e.preventDefault(); try { await api.post("/api/admin/facilities", resourceForm); setResourceForm({ name: "", kind: "CLASSROOM", capacity: "" }); loadSchedules(); } catch (e) { setError(e.response?.data?.detail || "تعذّرت إضافة المرفق"); } }
  async function addQuota(e) { e.preventDefault(); try { await api.post("/api/admin/subject-quotas", quotaForm); setQuotaForm({ level: "", subject: "", lessons_per_week: "1", minutes_per_lesson: "45" }); loadSchedules(); } catch (e) { setError(e.response?.data?.detail || "تعذّر حفظ الحجم الساعي"); } }
  async function saveConfig(e) { e.preventDefault(); try { await api.put("/api/admin/schedule-config", config); setError(""); notify("تم حفظ إعدادات الدوام"); } catch { setError("تعذّر حفظ إعدادات الدوام"); notify("تعذّر حفظ إعدادات الدوام", "error"); } }
  async function addSchedule(e) { e.preventDefault(); try { await api.post("/api/admin/schedules", schedule); setSchedule({ ...schedule, teacher_id: "", classroom_id: "" }); loadSchedules(); } catch (e) { setError(e.response?.data?.detail || "تعذّرت إضافة الحصة"); } }
  async function removeSchedule(id) { await api.delete(`/api/admin/schedules/${id}`); loadSchedules(); }
  async function generateSchedules() { try { const { data } = await api.post("/api/admin/schedules/generate", { school_year: config?.school_year }); setError(data.skipped?.length ? `تم إنشاء ${data.created} حصة، وتعذر وضع ${data.skipped.length} حصة بسبب نقص الخانات.` : `تم إنشاء ${data.created} حصة بنجاح.`); loadSchedules(); } catch (e) { setError(e.response?.data?.detail || "تعذّر إنشاء التوزيع الآلي"); } }
  async function approveSchedules() { try { const { data } = await api.post("/api/admin/schedules/approve"); setError(`تم اعتماد ${data.count} حصة رسميًا.`); notify(`تم اعتماد ${data.count} حصة رسميًا`); loadSchedules(); } catch { setError("تعذّر اعتماد التوزيع"); notify("تعذّر اعتماد التوزيع", "error"); } }
  async function exportSchedules() { try { const r = await api.get("/api/admin/schedules/export.xlsx", { responseType: "blob" }); const u = URL.createObjectURL(r.data), a = document.createElement("a"); a.href = u; a.download = "التوزيع-الأسبوعي.xlsx"; a.click(); URL.revokeObjectURL(u); } catch { setError("تعذّر تصدير التوزيع"); } }
  async function approveGrades() { await api.post("/api/admin/grades/approve", { term: gradeTerm, subject: gradeSubject }); loadGrades(); setError(""); }
  async function exportGrades() { try { const { data } = await api.get("/api/admin/grades/export.xlsx", { params: { term: gradeTerm, subject: gradeSubject }, responseType: "blob" }); const u = URL.createObjectURL(data), a = document.createElement("a"); a.href = u; a.download = `دفتر-النقاط-${gradeTerm}-${gradeSubject}.xlsx`; a.click(); URL.revokeObjectURL(u); } catch { setError("لا توجد نقاط معتمدة للتصدير أو تعذّر إنشاء الملف"); } }
  async function openProfile(type, id) { try { const { data } = await api.get(`/api/admin/${type}/${id}/profile`); setProfile({ ...data, type, id }); setProfileDraft(data.profile || {}); } catch { setError("تعذّر فتح البطاقة"); } }
  async function saveProfile() { try { await api.put(`/api/admin/${profile.type}/${profile.id}/profile`, profileDraft); setProfile(null); setError(""); } catch { setError("تعذّر حفظ البطاقة"); } }
  async function importStudents(e) { e.preventDefault(); if (!importFile || !importClass) return; const form = new FormData(); form.append("file", importFile); form.append("classroom_id", importClass); try { const { data } = await api.post("/api/admin/students/import", form, { headers: { "Content-Type": "multipart/form-data" } }); setImportResult(data); setImportFile(null); load(); } catch (e) { setError(e.response?.data?.detail || "تعذّر استيراد الملف"); } }
  async function previewStudents() { if (!importFile) return; const form = new FormData(); form.append("file", importFile); try { const { data } = await api.post("/api/admin/students/import/preview", form, { headers: { "Content-Type": "multipart/form-data" } }); setPreview(data); setError(""); } catch (e) { setError(e.response?.data?.detail || "تعذّرت معاينة الملف"); } }
  async function addUser(e) { e.preventDefault(); try { await api.post("/api/admin/users", null, { params: newUser }); setNewUser({ username: "", password: "", full_name: "", role: "TEACHER" }); notify("تم إنشاء الحساب"); load(); } catch (e) { setError(e.response?.data?.detail || "تعذّر إنشاء الحساب"); notify("تعذّر إنشاء الحساب", "error"); } }
  async function deactivateUser(id) { if (!window.confirm("هل تريد تعطيل هذا الحساب؟ لن يتمكن صاحبه من تسجيل الدخول.")) return; try { await api.put(`/api/admin/users/${id}/deactivate`); load(); } catch { setError("تعذّر تعطيل الحساب"); } }
  const cards = stats ? [["التلاميذ", stats.total_students, "students", "var(--brand)"], ["غياب اليوم", stats.absent_today, "attendance", "var(--warning)"], ["وجبات اليوم", stats.meals_served_today, "inventory", "var(--brand)"], ["تنبيهات المخزون", stats.low_stock_items, "inventory", stats.low_stock_items ? "var(--danger)" : "var(--brand)"], ...(budgetSummary ? [["تنفيذ الميزانية", `${budgetSummary.totals.utilization}%`, "budget", "var(--info)"]] : [])] : [];
  const nav = [["dashboard", "dashboard", "لوحة التحكم"], ["budget", "budget", LABELS.budget], ["absences", "attendance", "إدارة الغيابات"], ["students", "students", "التلاميذ والملفات"], ["grades", "grades", "نقاط التلاميذ"], ["schedule", "schedule", "التوزيع الأسبوعي"], ["resources", "inventory", "المرافق والمواقيت"], ["inventory", "inventory", "مخزون المطعم"], ["users", "users", "حسابات الطاقم"]];
  return <div className="admin-shell"><TopBar accent="var(--brand)" title={LABELS.admin} /><div className="admin-layout"><aside className="sidebar"><div className="side-title">نظام المدرسة<span>الإدارة المركزية</span></div>{nav.map(([id, icon, label]) => <button key={id} className={active === id ? "nav-item active" : "nav-item"} onClick={() => setActive(id)}><Icon name={icon} size={18} />{label}</button>)}<div className="side-footer">السنة الدراسية<br /><b>2026 / 2027</b></div></aside><main className="admin-main">
    <section className="welcome"><div><span className="eyebrow">الإدارة المدرسية</span><h1>صباح الخير، مدير المدرسة</h1><p>مركز المتابعة اليومية للحضور، المطعم، والموارد.</p></div><button className="refresh" onClick={load}>↻ تحديث البيانات</button></section>
    {toast && <Toast {...toast} onClose={() => setToast(null)} />}{error && <div className="alert">{error}</div>}{loading && !overview && <div className="loading">جارِ تجهيز لوحة المتابعة...</div>}
    {active === "dashboard" && <section className="metric-grid">{cards.map(([label, value, icon, color]) => <article className="metric" key={label}><div className="metric-icon" style={{ background: `${color}18`, color }}><Icon name={icon} size={22} /></div><div><strong>{value}</strong><span>{label}</span></div></article>)}</section>}
    {active !== "dashboard" && active !== "budget" && overview && <section className="section-hero"><span className="eyebrow">إدارة المدرسة</span><h1>{nav.find(n => n[0] === active)?.[2]}</h1><p>إدارة مركزية سهلة وواضحة لاتخاذ القرار اليومي.</p></section>}
    {active === "budget" && <BudgetManagement />}
    {active === "schedule" && <section className="panel schedule-actions"><div><h2>اعتماد التوزيع</h2><small>يعتمد المدير الجدول بعد المراجعة ويجهزه للنشر.</small></div><div className="panel-actions"><button className="primary" onClick={approveSchedules}>اعتماد التوزيع</button><button className="outline" onClick={exportSchedules}>تصدير Excel</button></div></section>}
    {active === "resources" && <div className="manage-grid"><form className="panel form-panel" onSubmit={addFacility}><h2>إضافة مرفق</h2><input required placeholder="اسم المرفق" value={resourceForm.name} onChange={e=>setResourceForm({...resourceForm,name:e.target.value})}/><select value={resourceForm.kind} onChange={e=>setResourceForm({...resourceForm,kind:e.target.value})}><option value="CLASSROOM">حجرة دراسية</option><option value="SPORT">ملعب</option><option value="ACTIVITY">قاعة نشاط</option><option value="CANTEEN">مطعم</option></select><input type="number" placeholder="الطاقة الاستيعابية" value={resourceForm.capacity} onChange={e=>setResourceForm({...resourceForm,capacity:e.target.value})}/><button className="primary">حفظ المرفق</button></form><form className="panel form-panel" onSubmit={addQuota}><h2>الحجم الساعي للمادة</h2><input required placeholder="المستوى: السنة الثالثة" value={quotaForm.level} onChange={e=>setQuotaForm({...quotaForm,level:e.target.value})}/><input required placeholder="المادة" value={quotaForm.subject} onChange={e=>setQuotaForm({...quotaForm,subject:e.target.value})}/><input required type="number" min="0.5" step="0.5" placeholder="حصص أسبوعيًا" value={quotaForm.lessons_per_week} onChange={e=>setQuotaForm({...quotaForm,lessons_per_week:e.target.value})}/><input type="number" min="15" placeholder="دقائق الحصة" value={quotaForm.minutes_per_lesson} onChange={e=>setQuotaForm({...quotaForm,minutes_per_lesson:e.target.value})}/><button className="primary">حفظ الحجم الساعي</button></form><section className="panel roster-panel"><h2>المرافق المسجلة</h2>{facilities.map(f=><div className="feature-row" key={f.id}><b>{f.name}</b><span>{f.kind} · السعة: {f.capacity || "غير محددة"}</span></div>)}<h2>المواقيت المسجلة</h2>{quotas.map(q=><div className="feature-row" key={q.id}><b>{q.subject}</b><span>{q.level} · {q.lessons_per_week} حصة × {q.minutes_per_lesson} د</span></div>)}</section></div>}
    {active === "schedule" && config && <form className="panel config-panel" onSubmit={saveConfig}><h2>إعداد دوام المؤسسة</h2><div className="report-actions"><select value={config.mode} onChange={e=>setConfig({...config,mode:e.target.value})}><option value="SINGLE">دوام واحد</option><option value="DOUBLE">دوامان</option></select><input value={config.school_year} onChange={e=>setConfig({...config,school_year:e.target.value})} placeholder="السنة الدراسية" /><label>بداية الصباح <input type="time" value={config.morning_start} onChange={e=>setConfig({...config,morning_start:e.target.value})}/></label><label>نهاية الصباح <input type="time" value={config.morning_end} onChange={e=>setConfig({...config,morning_end:e.target.value})}/></label><label>مدة الحصة <input type="number" min="20" value={config.lesson_minutes} onChange={e=>setConfig({...config,lesson_minutes:Number(e.target.value)})}/></label><button className="primary">حفظ إعداد الدوام</button><button type="button" className="outline" onClick={generateSchedules}>توليد التوزيع آليًا</button></div></form>}
    {active === "schedule" && overview && <section className="panel feature-panel"><div className="panel-head"><div><h2>إعداد التوزيع الأسبوعي</h2><small>العربية · الفرنسية · الإنجليزية · التربية البدنية</small></div><span className="count">{schedules.length} حصة</span></div><form className="staff-form" onSubmit={addSchedule}><select required value={schedule.teacher_id} onChange={e=>setSchedule({...schedule,teacher_id:e.target.value})}><option value="">اختر الأستاذ</option>{overview.users.filter(u=>u.role === "TEACHER").map(u=><option key={u.id} value={u.id}>{u.full_name}</option>)}</select><select required value={schedule.classroom_id} onChange={e=>setSchedule({...schedule,classroom_id:e.target.value})}><option value="">اختر القسم</option>{overview.classrooms.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select value={schedule.day} onChange={e=>setSchedule({...schedule,day:e.target.value})}>{["الأحد","الإثنين","الثلاثاء","الأربعاء","الخميس"].map((d,i)=><option key={i} value={i}>{d}</option>)}</select><select value={schedule.period} onChange={e=>setSchedule({...schedule,period:e.target.value})}><option value="MORNING">صباحية</option><option value="AFTERNOON">مسائية</option></select><button className="primary">إضافة الحصة</button></form><div className="schedule-grid">{[0,1,2,3,4].map(d=><div className="schedule-day" key={d}><h3>{["الأحد","الإثنين","الثلاثاء","الأربعاء","الخميس"][d]}</h3>{schedules.filter(s=>s.day===d).map(s=><div className="schedule-card" key={s.id}><b>{s.classroom}</b><span>{s.teacher}</span><small>{s.period === "MORNING" ? "صباحية" : "مسائية"}</small><button onClick={()=>removeSchedule(s.id)}>×</button></div>)}</div>)}</div></section>}
    {overview && active === "dashboard" && <div className="dashboard-grid"><section className="panel class-panel"><div className="panel-head"><div><h2>الحضور حسب الأقسام</h2><small>ملخص اليوم · {overview.date}</small></div><span className="live">● مباشر</span></div>{overview.classrooms.length ? overview.classrooms.map(c => <div className="class-row" key={c.id}><div><b>{c.name}</b><small>{c.students} تلميذ</small></div><div className="progress"><span style={{ width: `${c.students ? Math.min(100, c.absent / c.students * 100) : 0}%` }} /></div><b className={c.absent ? "danger-text" : "good-text"}>{c.absent} غائب</b></div>) : <p className="muted">لا توجد أقسام مسجلة بعد.</p>}</section>
      <section className="panel"><div className="panel-head"><div><h2>المخزون والتنبيهات</h2><small>متابعة احتياجات المطعم</small></div><span className="count">{overview.inventory.filter(i => i.low).length}</span></div>{overview.inventory.length ? overview.inventory.slice(0, 6).map(i => <div className="inventory-row" key={i.id}><span>{i.name}</span><b className={i.low ? "danger-text" : "good-text"}>{i.quantity} {i.unit}</b></div>) : <p className="muted">لا توجد مواد مخزنة.</p>}</section>
      <section className="panel users-panel"><div className="panel-head"><div><h2>الحسابات والصلاحيات</h2><small>المستخدمون المرتبطون بالنظام</small></div><span className="count">{overview.users.length}</span></div><div className="user-grid">{overview.users.map(u => <div className="user-chip" key={u.id}><span className="avatar">{u.full_name?.[0] || "؟"}</span><div><b>{u.full_name}</b><small>{roles[u.role] || u.role} · {u.active ? "حساب نشط" : "حساب معطل"} · <span className={u.online ? "status-online" : "status-offline"}>{u.online ? "متصل الآن" : "غير متصل"}</span></small></div></div>)}</div></section>
      <section className="panel"><div className="panel-head"><div><h2>آخر النشاطات</h2><small>سجل التدقيق الإداري</small></div></div>{logs.map(l => <div className="log-row" key={l.id}><span className="dot" /><div><b>{actions[l.action] || l.action}</b><small>{l.entity} #{l.entity_id ?? "-"}</small></div><time>{new Date(l.created_at).toLocaleTimeString("ar-DZ", { hour: "2-digit", minute: "2-digit" })}</time></div>)}</section></div>}
    <section className="panel report-panel"><div><h2>التقارير الإدارية</h2><p>أنشئ تقرير غياب رسميًا للفترة المطلوبة.</p></div><div className="report-actions"><input type="date" value={range.start} onChange={e => setRange(d => ({ ...d, start: e.target.value }))} /><span>إلى</span><input type="date" value={range.end} onChange={e => setRange(d => ({ ...d, end: e.target.value }))} /><button className="primary" onClick={exportPdf} disabled={exporting}>{exporting ? "جارِ الإنشاء..." : "تحميل تقرير PDF"}</button><button className="outline" onClick={exportAbsencesXlsx}>تحميل Excel</button></div></section>
    {active === "absences" && overview && <section className="panel feature-panel"><div className="panel-head"><div><h2>سجل الغياب والحضور</h2><small>راجع الحالات حسب التاريخ والقسم</small></div><span className="count">{absenceRows.length}</span></div><div className="report-actions"><input type="date" value={absenceRange.start} onChange={e => setAbsenceRange(r => ({ ...r, start: e.target.value }))} /><span>إلى</span><input type="date" value={absenceRange.end} onChange={e => setAbsenceRange(r => ({ ...r, end: e.target.value }))} /><select value={absenceClass} onChange={e => setAbsenceClass(e.target.value)}><option value="">كل الأقسام</option>{overview.classrooms.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select><button className="primary" onClick={loadAbsences}>بحث</button></div>{absenceRows.length ? absenceRows.map(a => <div className="feature-row" key={a.id}><b>{a.student_name}</b><span>{a.classroom} · {a.date}</span><em className="status-submitted">{a.period === "MORNING" ? "صباحية" : "مسائية"}</em></div>) : <p className="muted">حدد الفترة ثم اضغط بحث لعرض السجل.</p>}</section>}
    {active === "students" && overview && <section className="panel feature-panel"><div className="panel-head"><div><h2>ملفات التلاميذ</h2><small>الاسم، القسم، ورمز البطاقة</small></div><button className="primary" onClick={() => setShowManage(true)}>+ إضافة تلميذ</button></div><input className="student-search" placeholder="ابحث باسم التلميذ أو Barcode..." value={studentSearch} onChange={e => setStudentSearch(e.target.value)} /><form className="import-box" onSubmit={importStudents}><b>استيراد قائمة من Excel</b><small>يدعم أعمدة الاسم واللقب ورقم التعريف أو Barcode</small><div className="import-controls"><input type="file" accept=".xlsx,.xlsm" onChange={e => { setImportFile(e.target.files[0]); setPreview(null); }} /><select value={importClass} onChange={e => setImportClass(e.target.value)}><option value="">القسم المستهدف</option>{overview.classrooms.map(c => <option value={c.id} key={c.id}>{c.name}</option>)}</select><button type="button" className="outline" onClick={previewStudents}>معاينة</button><button className="primary">استيراد</button></div></form>{preview && <div className="preview-box"><b>معاينة آمنة · الصف {preview.header_row} · {preview.total_rows} صفًا</b><div className="preview-table"><table><thead><tr>{preview.headers.map((h, i) => <th key={i}>{h || `عمود ${i + 1}`}</th>)}</tr></thead><tbody>{preview.rows.map((row, r) => <tr key={r}>{preview.headers.map((_, i) => <td key={i}>{row[i] || ""}</td>)}</tr>)}</tbody></table></div></div>}{importResult && <div className="import-result">تمت إضافة {importResult.added} تلميذ · مكرر: {importResult.duplicates} · أخطاء: {importResult.invalid.length}</div>}{overview.classrooms.map(c => <details className="student-group" key={c.id}><summary><b>{c.name}</b><span>{c.students} تلميذ</span></summary>{c.studentsList?.filter(s => `${s.full_name} ${s.barcode}`.toLowerCase().includes(studentSearch.toLowerCase())).map(s => <div className="feature-row" key={s.id}><b>{s.full_name}</b><span>Barcode: {s.barcode}</span><button className="outline" onClick={() => openProfile("students", s.id)}>فتح الملف</button></div>)}</details>)}</section>}
    {active === "grades" && <section className="panel feature-panel"><div className="panel-head"><div><h2>مراجعة واعتماد النقاط</h2><small>استقبال دفاتر الأساتذة قبل اعتمادها</small></div><div className="panel-actions"><button className="primary" onClick={approveGrades} disabled={!gradeRows.some(r => r.status === "SUBMITTED")}>اعتماد المرسل</button><button className="outline" onClick={exportGrades} disabled={!gradeRows.some(r => r.status === "APPROVED")}>تصدير Excel</button></div></div><div className="report-actions"><select value={gradeTerm} onChange={e => setGradeTerm(e.target.value)}><option>الفصل الأول</option><option>الفصل الثاني</option><option>الفصل الثالث</option></select><input value={gradeSubject} onChange={e => setGradeSubject(e.target.value)} placeholder="المادة" /><button className="outline" onClick={loadGrades}>تحميل الدفتر</button></div>{gradeRows.length ? gradeRows.map(r => <div className="feature-row" key={r.id}><b>{r.student_name}</b><span>{r.classroom} · التقويم: {r.continuous ?? "—"} · الاختبار: {r.exam ?? "—"}</span><em className={`status-${r.status.toLowerCase()}`}>{r.status === "SUBMITTED" ? "بانتظار الاعتماد" : r.status === "APPROVED" ? "معتمد" : "مسودة"}</em></div>) : <p className="muted">اختر الفصل والمادة ثم اضغط تحميل الدفتر.</p>}</section>}
    {active === "inventory" && overview && <section className="inventory-page"><form className="panel form-panel" onSubmit={addInventory}><h2>إضافة سلعة للمخزون</h2><p>أضف المنتج مع صورة وبياناته الأساسية.</p><input required placeholder="اسم المنتج" value={newItem.name} onChange={e => setNewItem({ ...newItem, name: e.target.value })} /><input required type="number" min="0" step="0.1" placeholder="الكمية" value={newItem.quantity} onChange={e => setNewItem({ ...newItem, quantity: e.target.value })} /><select value={newItem.unit} onChange={e => setNewItem({ ...newItem, unit: e.target.value })}><option>كغ</option><option>لتر</option><option>علبة</option><option>قطعة</option></select><input type="number" min="0" placeholder="حد التنبيه" value={newItem.low_stock_threshold} onChange={e => setNewItem({ ...newItem, low_stock_threshold: e.target.value })} /><input placeholder="رابط صورة المنتج (اختياري)" value={newItem.image_url} onChange={e => setNewItem({ ...newItem, image_url: e.target.value })} /><button className="primary">حفظ المنتج</button></form><section className="panel product-panel"><div className="panel-head"><div><h2>قائمة السلع</h2><small>المخزون الحالي والتنبيهات</small></div></div><div className="product-grid">{overview.inventory.map(i => <article className="product-card" key={i.id}><div className="product-image">{i.image_url ? <img src={i.image_url} alt={i.name} /> : <span aria-label="صورة غير متوفرة"><Icon name="inventory" size={28} /></span>}</div><b>{i.name}</b><strong className={i.low ? "danger-text" : "good-text"}>{i.quantity} {i.unit}</strong><small>{i.low ? "يحتاج إلى تموين" : "المخزون جيد"}</small></article>)}</div></section></section>}
    {active === "users" && overview && <section className="panel feature-panel"><div className="panel-head"><div><h2>حسابات الطاقم</h2><small>المدير يتحكم في حسابات الأساتذة ومشرف المطعم</small></div><span className="count">{overview.users.length}</span></div><form className="staff-form" onSubmit={addUser}><input required placeholder="اسم المستخدم" value={newUser.username} onChange={e => setNewUser({ ...newUser, username: e.target.value })} /><input required type="password" placeholder="كلمة المرور" value={newUser.password} onChange={e => setNewUser({ ...newUser, password: e.target.value })} /><input required placeholder="الاسم الكامل" value={newUser.full_name} onChange={e => setNewUser({ ...newUser, full_name: e.target.value })} /><select value={newUser.role} onChange={e => setNewUser({ ...newUser, role: e.target.value })}><option value="TEACHER">أستاذ</option><option value="RESTAURANT_MANAGER">مشرف المطعم</option></select><button className="primary">إنشاء الحساب</button></form>{overview.users.map(u => <div className="feature-row" key={u.id}><span className="avatar">{u.full_name?.[0]}</span><b>{u.full_name}</b><span>{roles[u.role]}</span><button className="outline" onClick={() => openProfile("users", u.id)}>البطاقة المهنية</button>{u.active && u.id !== Number(localStorage.getItem("user_id")) && <button className="danger-action" onClick={() => deactivateUser(u.id)}>تعطيل</button>}<em className={u.active ? "status-approved" : "status-draft"}>{u.active ? "نشط" : "معطل"}</em></div>)}</section>}
    {profile && <div className="profile-overlay" onClick={() => setProfile(null)}><section className="profile-card" onClick={e => e.stopPropagation()}><button className="close-profile" onClick={() => setProfile(null)}>×</button><div className="profile-photo">{profile.profile?.photo_url ? <img src={profile.profile.photo_url} alt="" /> : "👤"}</div><h2>{profile.student?.name || profile.user?.name}</h2><p>{profile.student ? `${profile.student.classroom} · ${profile.student.barcode}` : `${roles[profile.user?.role] || "طاقم المدرسة"} · ${profile.user?.username}`}</p><div className="profile-edit-grid">{(profile.student ? [["parent_name", "اسم الولي"], ["parent_phone", "هاتف الولي"], ["address", "العنوان"], ["birth_date", "تاريخ الميلاد"], ["national_id", "رقم التعريف"], ["health_notes", "ملاحظات صحية"], ["photo_url", "رابط الصورة"]] : [["specialty", "التخصص"], ["phone", "الهاتف"], ["email", "البريد الإلكتروني"], ["hire_date", "تاريخ التوظيف"], ["address", "العنوان"], ["photo_url", "رابط الصورة"]]).map(([key, label]) => <label key={key}>{label}<input value={profileDraft[key] || ""} onChange={e => setProfileDraft({ ...profileDraft, [key]: e.target.value })} /></label>)}</div><button className="primary profile-save" onClick={saveProfile}>حفظ البطاقة</button>{profile.student && <div className="profile-summary"><div><b>{profile.absences?.length || 0}</b><small>سجل غياب</small></div><div><b>{profile.grades?.length || 0}</b><small>مادة مسجلة</small></div><div><b>{profile.meals?.length || 0}</b><small>وجبة</small></div></div>}</section></div>}
    {active === "dashboard" && <section className="manage-toggle"><button className="primary" onClick={() => setShowManage(v => !v)}>{showManage ? "إخفاء الإدارة التفصيلية" : "فتح إدارة الأقسام والتلاميذ"}</button></section>}
    {showManage && overview && <section className="manage-grid"><form className="panel form-panel" onSubmit={addClass}><h2>إضافة قسم</h2><p>أنشئ قسمًا جديدًا للمدرسة.</p><input placeholder="مثال: السنة الثالثة أ" value={newClass} onChange={e => setNewClass(e.target.value)} /><button className="primary">حفظ القسم</button></form><form className="panel form-panel" onSubmit={addStudent}><h2>إضافة تلميذ</h2><p>أضف التلميذ واربطه بقسمه.</p><input placeholder="الاسم واللقب" value={newStudent.full_name} onChange={e => setNewStudent({ ...newStudent, full_name: e.target.value })} /><input placeholder="رمز البطاقة / Barcode" value={newStudent.barcode} onChange={e => setNewStudent({ ...newStudent, barcode: e.target.value })} /><select value={newStudent.classroom_id} onChange={e => setNewStudent({ ...newStudent, classroom_id: e.target.value })}><option value="">اختر القسم</option>{overview.classrooms.map(c => <option value={c.id} key={c.id}>{c.name}</option>)}</select><button className="primary">حفظ التلميذ</button></form><section className="panel roster-panel"><h2>سجل الأقسام والتلاميذ</h2>{overview.classrooms.map(c => <details key={c.id}><summary><b>{c.name}</b><span>{c.students} تلميذ</span></summary><div className="roster-list">{c.studentsList?.map(s => <div key={s.id}>{s.full_name}<small>{s.barcode}</small></div>) || <span className="muted">افتح التحديث لرؤية القائمة التفصيلية.</span>}</div></details>)}</section></section>}
  </main></div></div>;
}
